name: Node.js CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # local version of node
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run Database Migrations
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} #change name of secret if needed
        run: npm run migrate

      - name: Run tests
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }} #also change here
        run: npm test
